blog/blog/config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :mountains do
    resources :comments, only: [:create, :destroy, :update] #No tiene sentido que este solo, entonces se anida a mountains
  end
  devise_for :users
  root 'welcome#index'

  get '/dashboard', to: "welcome#dashboard"

  #Como la accion publicar modifica un elemento, entonces se utiliza put
  put "/mountains/:id/publish", to: "mountains#publish"
  put "/mountains/:id/unpublish", to: "mountains#unpublish"
end

blog/blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	# El admin podrá acceder al dashboard para publicar montañas
	before_action :authenticate_admin!, only: [:dashboard]

	def index

	end

	def dashboard
		@estadoRecibido = params[:estado]
		if @estadoRecibido === "borradores"
			@mountains = Mountain.paginate(page: params[:page], per_page: 3).borradores
		else
			@mountains = Mountain.paginate(page: params[:page], per_page: 3).publicados
		end
	end
end

blog/blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/blog/app/views/welcome/dashboard.html.erb
<div class="row">
	<% @mountains.each do |mountain| %>
		<div class="col-xs-12
                col-sm-8
                col-md-6
                col-lg-4">
			<div class="card" id="cardContainer">

			  <div class="card-header">
			    <%= mountain.name %> 
			  </div>

			  <div class="card-body">
			    <blockquote class="blockquote mb-0">
			    	
			        <p id="tituloTexto"> Descripcion: </p>
			      	<p id="contenidoTexto"> <%= sanitize truncate(mountain.description.html_safe, length:30) %> </p>


			        <% unless mountain.user.nil? %>
			      		<p id="tituloTexto"> Escrito por: </p> 
			      		<p id="contenidoTexto"> <%= mountain.user.email %>  </p>
			        <% end %>

			        <p id="tituloTexto"> Visualizaciones </p> 
			      	<p id="contenidoTexto"> <%= mountain.visits_count %> usuarios han visualizado este cerro.</p>

			        <footer class="blockquote-footer"> 
			      		<p> Altitud: <%= mountain.altitude %></p>
			        </footer>

			        <div class="btn-group">
			        	<%= link_to "Borrar", mountain, class:"btn btn-danger", method: :delete %>
			        </div>

			        <div class="btn-group">
			        	<%= link_to "Editar", edit_mountain_path(mountain), class:"btn btn-warning"%>
			        </div>

			        <div class="btn-group">
			        	<%= link_to "Ver más", mountain_path(mountain), class:"btn btn-info"%>
			        </div>
			        
			        <% if mountain.may_publish? %>
				        <div class="btn-group">
					       <%= link_to "Publicar", "/mountains/#{mountain.id}/publish", 
					       class:"btn btn-dark", method: :put%>
					   	</div>

				    <% else %>
				    	<div class="btn-group">
					       <%= link_to "Retirar publicacion", "/mountains/#{mountain.id}/unpublish", 
					       class:"btn btn-dark", method: :put%>
					   </div>
				    <%end%>

			    </blockquote>
			  </div>
			</div>
		</div>
	<% end %>

	<%= will_paginate @mountains %>
</div>	

blog/blog/app/views/welcome/index.html.erb
<div class="center-xs">
	<% if user_signed_in? %>
		<h2>Bienvenido <%= current_user.email %> </h2>
	<% else %>
		<h2>Bienvenido al blog de los cerros de Santiago </h2>
	<% end %>
</div>