blog/blog/config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :mountains do
    resources :comments, only: [:create, :destroy, :update] #No tiene sentido que este solo, entonces se anida a mountains
  end
  devise_for :users
  root 'welcome#index'

  get '/dashboard', to: "welcome#dashboard"

  #Como la accion publicar modifica un elemento, entonces se utiliza put
  put "/mountains/:id/publish", to: "mountains#publish"
  put "/mountains/:id/unpublish", to: "mountains#unpublish"
end

blog/blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :mountain
end

blog/blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:update, :destroy]
  before_action :set_mountain
  before_action :authenticate_user!

  

  # El editor además de ver y crear comentarios, podrá editar uno.
  before_action :authenticate_editor!, only: [:update]

  # El admin tendrá tambien las funciones del editor, pero especificamente puede destruir también.
  before_action :authenticate_admin!, only: [:destroy]


  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.mountain = @mountain

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.mountain, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment.mountain }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.mountain, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @mountain, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_mountain
      @mountain = Mountain.find(params[:mountain_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :mountain_id, :body)
    end
end

blog/blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/blog/app/views/comments/_form.html.erb
<%= form_with(model: [@mountain, @comment], remote: true, html: {id: "comments-form"}) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>﻿

  <div class="card", id="containerCommentForm">
    <div class="card-body">
      <h5 class="card-title">Comentar</h5>
      <div class="field">
        <%= form.text_area :body, class:"form-control", id:"text-areaNotResize", placeholder:"Ingresa un comentario" %>
      </div>

      <div class="actions">
        <%= form.submit :Enviar, class:"btn btn-primary", id:"buttonSendCommentary"%>
        <%= link_to "Volver", "/mountains", class:"btn btn-primary", id:"buttonBack"%>
      </div>
    </div>
  </div>
<% end %>

blog/blog/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

blog/blog/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

blog/blog/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Mountain:</strong>
  <%= @comment.mountain %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>